오류는 크게 2가지로 나뉘는데 프로그램 코드 작성 중 발생하는 컴파일 오류와 실행 중인 프로그램이 의도하지 않은 동작을 하거나 프로그램이 중지하는 실행 오류가 있다.(실행 오류에서 프로그램을 잘못 구현하여 의도한 바와 다르게 실행되어 생기는 오류를 버그라고 한다.)

실행 오류는 수정하기 쉬운 컴파일 오류와 달리 예측하기 어렵고 매우 심각한 문제가 될 수 있기 때문에 오류 원인을 찾을 수 있도록 프로그램을 개발할 때 로그를 정확하게 남기는 것이 중요하다.(프로그램 실행 중에 발생하는 여러 상황을 기록한 내용을 로그라고 하고 파일에 기록한다. 이 파일을 로그 파일이라고 한다.)

예외 처리의 주된 목적은 프로그램이 비정상 종료되는 것을 방지하기 위한 것이고 예외가 발생했을 때 로그를 남겨 두면 예외 상황을 파악하고 버그를 수정하는데 도움을 받을 수 있다.

실행 오류는 시스템 오류와 예외가 있다. 시스템 오류는 자바 가상 머신에서 발생하는 오류로 프로그램에서 제어 할 수 없다. 이에 반해 예외는 제어 가능하다.
 
오류 클래스는 모두 Throwable 클래스에서 상속받는다. Error클래스는 시스템 오류를 다루고 프로그램에서 제어하는 부분은 Exception클래스. 예외 클래스의 최상위 클래스는 Exception 클래스이다. 개발 환경에 따라 예외가 발생하면 대부분 처리하라는 컴파일 오류 메시지를 띄운다. 하지만 RuntimeException 클래스는 try-catch문을 사용하여 예외 처리를 하지 않아도 컴파일 오류 발생하지 않기 때문에 알아서 처리해야 한다.

가장 기본적인 예외 처리의 문법은 다음과 같은데, try 블록에는 예외가 발생할 수 있는 코드를 작성하고 try 블록 안에서 예외가 발생하면 catch 블록이 수행된다. catch문의 예외 타입은 예외 상황에 따라 달라진다. 

자바에서 제공하는 많은 예외 클래스들은 컴파일러에 의해 처리되기 때문에 이런 경우 자바에서는 예외 처리를 하지 않으면 컴파일 오류가 발생한다. 예외 처리를 한다고 해서 프로그램의 예외 상황 자체를 막을 수는 없지만 예외 처리를 하면 예외 상황을 알려 주는 메시지를 볼 수 있고, 프로그램이 비정상 종료되지 않고 계속 수행된다.

프로그램에서 사용한 자원은 프로그램이 종료되면 자동으로 해제되지만 끝나지 않고 계속 수행되는 서비스 같은 경우 사용한 자원을 반드시 close() 메서드로 닫아야 한다. 무조건 수행되는 finally 블록에서 close()를 구현하면 이를 쉽게 해결할 수 있다.(try,catch문에 return문이 있어도 수행된다.) 그러므로 파일,네트워크,데이터베이스에 연결한 경우 연결을 닫는 close() 코드를 finally 블록에서 수행한다.

자바 7부터 제공하는 try-with-resources문은 close() 메서드를 호출하지 않아도 try 블록 내에서 열린 자원을 자동으로 닫을 수 있다.(정상 종료,예외 발생 모두 자원이 잘 해제된다.) 이 문법을 사용하려면 해당 자원이 AutoCloseable 인터페이스를 구현해야 한다. AutoCloseable 인터페이스에는 close() 메서드가 있고 이를 구현한 클래스는 close()를 명시적으로 호출하지 않아도 close() 메서드 부분이 호출된다. FileInputStream, 네트워크,데이터베이스 관련 클래스가 AutoCloseable 인터페이스를 구현하고 있다. AutoCloseable 인터페이스는 close() 메서드를 반드시 구현해야 한다.(throw new Exception() 문장을 사용하면 프로그램에서 강제로 예외를 발생시켜 catch 블록이 수행되도록 구현할 수 있다.)

자바 9에서 추가된 향상된 try-with-resources문의 경우 AutoCloseable 인터페이스를 구현한 자원의 변수를 try문 괄호 안에서 선언해야 하는 자바 7과 달리 외부에서 선언한 변수를 그대로 쓸 수 있다.

throws는 예외를 처리하지 않고 미룬다고 선언한 후 메서드를 호출하여 사용하는 부분에서 예외를 처리하는 방법이다. 

예외를 예측할 수 없는 상황에서 모든 예외 상황을 처리하고자 한다면 맨 마지막 부분에 Exception 클래스를 활용하여 catch 블록을 추가한다. Exception 클래스는 모든 예외 클래스의 최상위 클래스기 때문에 Exception 클래스로 자동으로 형 변환이 된다.(Exception 클래스를 기본 예외 처리라고 한다.) 예외는 catch문을 선언한 순서대로 검사하기 때문에 맨 위에 catch(Exception e) 문장을 쓰면 발생하는 모든 예외 클래스가 Exception 클래스로 자동 형 변환되어 오류가 발생한다. 그래서 기본 예외 처리는 가장 아래에 둔다.

사용자 정의 예외 클래스를 구현할 때는 기존 JDK에서 제공하는 예외 클래스 중 가장 유사한 클래스를 상속받거나 유사한 예외 클래스를 잘 모르겠다면 가장 상위 클래스인 Exception 클래스에서 상속 받는다.

프로그램을 개발할 때는 로그를 남기는 것이 매우 중요하다. 오류가 발생했을 때 로그를 보고 오류가 발생하는 코드를 순서대로 따라가면 확인할 수 있고 원인을 찾을 수 있다.
로그의 정보 의미에 따라 레벨을 나누어 관리한다.

나 혼자 코딩! 문제가 있는데 아직 못 풀어서 나중에 풀면 업데이트. 다음이 입출력인데 입출력 너무 많다....
